### ISSUE TITLE
Problem with smartphone router

### ISSUE THREAD

**Issue by AlphaOmega3** [hypeapps/Endoscope#12]
Hello! first, the app works well on normal network (LAN connected to the Internet), but when I tried to use a third cell as router (and thus to create a "private" network, without Internet access), does not work! you could solve somehow ??

**Comment by hypeapps** [comment]
Hi @AlphaOmega3, well I tried to connect dvieces that way. I not figured out how to allow connecting devieces via hotspot function. If you know how to make this possible I will be happy. You can fork my repository.

**Comment by AlphaOmega3** [comment]
Mmh apparently the app can not send / receive the IP address of the connection via the router .. (I hope that is not a question idiot) it would be possible to use something else (instead of an IP) to communicate, something that steps without problems ?? like an internal code app based on Mac Adress of devices or the IMEI code..?

**Comment by hypeapps** [comment]
App using libstreaming library which using RTSP protocol to make stream possible. RTSP connect path must by that way rtsp://addres_ip:host/ only

**Comment by AlphaOmega3** [comment]
Then I have a proposal alternative: support USB. let me explain: instead of using the LAN, it would be possible to add an ability to connect 1 or more smartphones with a cable USB and / or with a USB cam/s ? if feasible, it would be comfortable have all in a app alone, but also 2 would not be evil. es Endoscope LAN and Endoscope USB ... who says ??

**Comment by hypeapps** [comment]
@AlphaOmega3 Everything is possible! :+1: 
But now I focused on my new project called Episodie you can look at: [Episodie](https://github.com/hypeapps/Episodie)

For now Endscope must be WiFi only. 

I am very grateful for your ideas and feedback!

**Comment by AlphaOmega3** [comment]
Ok, thanks anyway
