### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by AlfaOmega33** [hypeapps/Endoscope#13]
All right, since it is not possible (at the time!) to use the app without internet access, you may add encryption to secure the connection??

**Comment by OffifialMITX** [comment]
Well, you already have some seconds delay, if everething is being en- and decrypted it would:
1. Take even more time especially if you don't have a high-end device
2. Requie much more power

Also it doesn't requie an internet connection. You can also turn your mobile data of and create a hotspot, then stream from the other device.
