### ISSUE TITLE
Packaging for F-Droid

### ISSUE THREAD

**Issue by est31** [hypeapps/Endoscope#5]
Hello, I want to package this app for the [F-Droid](https://f-droid.org) app store which only has builds of open source apps.

There is one minor issue with your app: you don't seem to increase the `versionCode` and `versionName` in the build.gradle. This is important for google play as it is for f-droid. As f-droid only takes the source code from upstream, f-droid needs the versionCode to be updated from inside git.

I see the app on google play has version 1.1 already. Can you remember to also push the version updates to the github repository, so that f-droid can track that?

In the ideal case, update the versions in one commit, and then tag that commit with a git tag. This way, f-droid can be set up to automatically update your application.

**Comment by hypeapps** [comment]
Hello, I pushed the latest version (1.2). Already versionCode is up to date.

**Comment by est31** [comment]
many thanks! I'll add it to f-droid very soon.
